package com.my.greendao_search.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CASE".
 */
public class Case {

    private Long id;
    private String name;
    private Long time;
    private Integer age;

    public Case() {
    }

    public Case(Long id) {
        this.id = id;
    }

    public Case(Long id, String name, Long time, Integer age) {
        this.id = id;
        this.name = name;
        this.time = time;
        this.age = age;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

}
